name: joel_osteen_sermons
description: Joel Oesteen Sermons

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  animations: ^2.0.2
  just_audio: ^0.9.18
  audio_service: ^0.18.3
  audio_session: ^0.1.6+1
  rxdart: ^0.27.3
  webfeed: ^0.7.0
  http: ^0.13.4
  share: ^2.0.4
  url_launcher: ^6.0.17
  flutter_riverpod: ^1.0.3
  get_storage: ^2.0.3
  google_fonts: ^2.1.1
  intl: ^0.17.0
  get_it: ^7.2.0
  lottie: ^1.2.1
  marquee: ^2.2.0
  youtube_explode_dart: ^1.10.8
#  permission_handler: ^8.3.0
  path_provider: ^2.0.8
  cached_network_image: ^3.2.0
  google_mobile_ads: ^0.13.3
  flutter_admob_app_open: ^1.1.1
  facebook_audience_network: ^1.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.3.2
#  flutter_launcher_icons: ^0.9.2

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/icon.png"
  color_dark: "#042a49"
  android: true
  ios: false
#flutter_icons:
#  android: true
#  ios: false
#  image_path: "assets/images/icon.png"


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/json/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

    #  flutter pub run flutter_launcher_icons:main
#    flutter pub run flutter_native_splash:create